with open('js/engine/Game.js', 'r', encoding='utf-8', errors='replace') as f:
    lines = f.readlines()

# Replace lines 520-536 (1-indexed) -> indices 519-535 (0-indexed)
new_block = [
    "    _executeAssistantCommand(comId) {\n",
    "        this._assistantParticipatedThisTrain = true;\n",
    "        const assi = this.getAssi();\n",
    "        const target = this.getTarget();\n",
    "        if (comId === 900) {\n",
    "            if (!assi) { UI.appendText(`没有助手，无法代行。\\n`, \"warning\"); return; }\n",
    "            // 检查助手临时体力（<20%无法代行）\n",
    "            const assiStaminaPct = (assi._assistantMaxStamina || 80) > 0 ? (assi._assistantStamina / (assi._assistantMaxStamina || 80)) : 1;\n",
    "            if (assiStaminaPct < 0.20) {\n",
    "                UI.appendText(`【${assi.name}体力不足，无法代行...（${assi._assistantStamina}/${assi._assistantMaxStamina}）】\\n`, \"warning\");\n",
    "                return;\n",
    "            }\n",
    "            UI.appendText(`\\n${assi.name}代替魔王执行调教，${target.name}的体验略有不同……\\n`, \"info\");\n",
    "            this.trainSystem.execute(this.selectcom >= 0 ? this.selectcom : 0);\n",
    "            // 主奴获得90%PALAM（代行不如魔王熟练）\n",
    "            for (let i = 0; i < target.palam.length; i++) {\n",
    "                if (target.palam[i] > 0) target.palam[i] = Math.floor(target.palam[i] * 0.9);\n",
    "            }\n",
    "            // 消耗助手体力\n",
    "            assi._assistantStamina -= 15;\n",
    "            if (assi.energy !== undefined) assi.energy -= 5;\n",
    "            // 代行后下回合自动休息\n",
    "            assi._assistantRestNextTurn = true;\n",
    "            UI.appendText(`【${assi.name}代行后需要休息一回合】\\n`, \"dim\");\n",
    "        } else if (comId === 901) {\n",
    "            if (!assi) { UI.appendText(`没有助手，无法参与。\\n`, \"warning\"); return; }\n",
    "            // 检查助手体力\n",
    "            if (assi._assistantStamina <= 0) {\n",
    "                UI.appendText(`【${assi.name}已经脱力，无法参与...】\\n`, \"warning\");\n",
    "                return;\n",
    "            }\n",
    "            UI.appendText(`\\n${assi.name}加入了调教，${target.name}的快感倍增！\\n`, \"info\");\n",
    "            this.trainSystem.execute(this.selectcom >= 0 ? this.selectcom : 0);\n",
    "\n",
    "            // 同性/同路线检测\n",
    "            const sameSex = (assi.talent[121] && target.talent[121]) || (assi.talent[122] && target.talent[122]);\n",
    "            const sameRoute = (assi.mainRoute >= 0 && assi.mainRoute === target.mainRoute);\n",
    "            let bonuses = [];\n",
    "            if (sameSex) bonuses.push(\"同性共鸣：羞耻+20%\");\n",
    "            if (sameRoute) bonuses.push(\"同路线共鸣：+25%\");\n",
    "            if (bonuses.length > 0) UI.appendText(`【${bonuses.join(\"、\")}】\\n`, \"info\");\n",
    "\n",
    "            // 主奴部位快感加成\n",
    "            if (target.addPartGain) {\n",
    "                for (let i = 0; i < 8; i++) {\n",
    "                    let boost = 0.2;\n",
    "                    if (sameRoute) boost += 0.25;\n",
    "                    target.addPartGain(i, Math.floor((target.partGauge[i] || 0) * boost));\n",
    "                }\n",
    "            }\n",
    "            // 助手获得70%PALAM（简化）\n",
    "            if (assi.addPartGain) {\n",
    "                for (let i = 0; i < 8; i++) {\n",
    "                    let ratio = 0.7;\n",
    "                    if (sameSex) ratio += 0.20;\n",
    "                    if (sameRoute) ratio += 0.25;\n",
    "                    assi.addPartGain(i, Math.floor((target.partGauge[i] || 0) * ratio));\n",
    "                }\n",
    "            }\n",
    "\n",
    "            // 消耗助手体力\n",
    "            assi._assistantStamina -= 10;\n",
    "            if (assi.energy !== undefined) assi.energy -= 3;\n",
    "\n",
    "            // 检查助手脱力\n",
    "            if (assi._assistantStamina <= 0) {\n",
    "                UI.appendText(`【${assi.name}在参与中脱力了...】\\n`, \"danger\");\n",
    "            }\n",
    "        }\n",
    "    }\n",
]

new_lines = lines[:519] + new_block + lines[536:]
with open('js/engine/Game.js', 'w', encoding='utf-8') as f:
    f.writelines(new_lines)
print('OK')
